# BACKGROUND {.unnumbered}

Chicken meat and eggs provide a critical source of protein globally. Demand in Sub-Saharan Africa for poultry meat is projected to grow by 121% between 2005-2050 [@erdaw2022]. In Maputo, Mozambique and many other African cities, informal markets, described as unregulated or poorly regulated markets [@grace2010], and wet or live markets, where livestock are purchased live and butchered on-site [@naguib2021], comprise a significant portion of the food sector [@raimundo]. The United Nations Human Settlement Program has described informal economies as, "the dominant modes of economic life in most sub-Saharan African cities,"[@raimundo]; [@towards] Informal and live animal markets provide a nexus at which humans and livestock come into close contact, and where livestock are processed, often without adequate access to clean water[@naguib2021]. These settings can pose a significant risk of foodborne disease transmission. African countries bear the greatest burden of foodborne illness; the WHO region including Mozambique reports foodborne illness burden of 1,200 disability-adjusted life-year (DALYs) per 100,000 people [@havelaar2015]. Poultry in particular appears to pose acute risks; in Ethiopia and Burkina Faso , poultry represented the greatest source of foodborne illness compared with other meat and vegetable products, representing an annual burden of 65,000 and 42,600 DALYs, respectively[@havelaar2022]. A recent study in Maputo, Mozambique reported significantly higher concentrations of Salmonella enterica and Campylobacter spp. DNA in poultry carcass meat at live bird markets than at farms, suggesting amplification along the value chain[@foodsaf]. While absolute quantification of specific pathogens in chickens can help inform risk assessment, the diversity of pathogens that may be contaminating these products remains unknown. Poultry carcasses sold at informal or wet markets in Mozambique and other African LMICs pose additional human health risks. Nontherapeutic antibiotics are often administered through chicken feed to improve growth and reduce disease, with consequences for the selection of antibiotic resistance. A global review of national monitoring programs from 8 countries in the Americas, Asia, and Europe reported that average resistance to common antibiotic classes among E. coli exceeded 40% in these countries, with lower prevalence of resistance to specific classes in countries where those classes are banned for use in poultry[@roth2019]. A similar review found widespread antibiotic resistance in E. coli among poultry and other livestock in African countries[@alonso2017] . Prior studies using culture-based or qPCR methods to quantify pathogen load on poultry carcasses do not provide insight into the diversity of antibiotic resistance genes (ARGs) present on these food products, which can pose major public health risks when mobilized by human pathogens. Metagenomic sequencing of total DNA is an increasingly popular tool to characterize entire microbial communities (i.e., the microbiome) in food and environmental samples, including the ARGs they harbor (i.e., the resistome). To date, studies using metagenomic approaches to characterize poultry microbiomes and resistomes have largely been conducted in higher income countries[@yang2022] [@xu2022] [@segura-wang2021] while metagenomic analyses of poultry in LMICs remain limited. Differential human health hazards presented by commercial and indigenous chicken breeds also remain unclear in these settings. Despite growth in commercial chicken breeds worldwide, indigenous chicken breeds remain common protein sources in Asia and Africa. Indigenous chicken breeds represented about 80% of chickens raised in low- and middle-income countries (LMICs) in Africa and Asia as of 2006 [@pym2006], and more recent figures report approximately 70% in Rwanda and Kenya as of 2015 [@mujyambere2022]. In a study of poultry farms and domestic chickens in Ecuador, significantly higher levels of antibiotic-resistance were measured among commercially raised chickens than among household chickens [@braykov2016] Indigenous chickens are typically locally adapted and resistant to regionally circulating disease [@psifidi2016], but immunity nevertheless remains a chief concern among indigenous chicken farmers in Kenya [@okeno2012]. While broiler and layer chicken breeds have been bred to optimize feed efficiency and growth, this may come at the cost of immune traits [@miyumo2023]. For example, greater resistance to S. typhimurium infection among indigenous chicken breeds than among broiler chicken breeds [@dar2022] suggests that immune regulation may be compromised in broiler and layer chickens as compared with indigenous breeds, necessitating prophylactic antibiotic use in commercial chicken production. It remains unclear whether commercial and indigenous chickens bear different microbiomes or resistomes and therefore may represent different hazards to human health.

This study was nested within the ChEEP ChEEP (Chicken Exposures and Enteric Pathogens in Children Exposed through Environmental Pathways) study, which aimed to identify pathways of exposure to enteric pathogens among children in Maputo, Mozambique. Prior findings from the ChEEP ChEEP study suggest that children experience routine exposures to live and butchered chickens at their homes and local markets [@lamar2023]. This study employs metagenomic sequencing data from chicken samples to further characterize pathogenic and antimicrobial resistant bacteria to which these children may be exposed.
