# Results {-}

## Fecal Samples
Overall, we identified 22,986 bacterial species in chicken fecal samples, of which 10 (<1%) were uniquely identified in commercial chickens and 17 (<1%) were uniquely identified in indigenous chickens. Bacterial reads comprised 49% of total reads in fecal samples (Table 1), on average. One hundred eighteen (0.5%) of unique bacterial species and 13% of bacterial reads detected in chicken feces were established human pathogens. All detected pathogens were observed in both commercial and indigenous chicken feces. We detected 164 unique ARGs in fecal samples, of which 60 (37%) were uniquely identified among commercial chickens and 28 (17%) were uniquely identified among indigenous chickens. Among all ARGs identified in fecal samples, 36 (22%) were identified as HR-ARGs. Of these HR-ARGs, 8 (22%) were uniquely detected in commercial chickens and 5 (14%) were uniquely detected in indigenous chickens. We identified substantially fewer bacterial reads in chicken processing samples, including carcass rinse (16% of total reads among commercial and 6% of total reads among indigenous chickens, on average) and rinse water samples (27% on average), likely reflecting high degrees of contamination by host DNA from chickens, humans, and other sources. 

### Commercial and indigenous chicken fecal pathogens and resistomes are compositionally distinct at production sites. 
Bacterial pathogens and ARGs differed between commercial and indigenous chickens (Ppathogens=0.003, PARGs=0.018) at production sites, i.e., farms for commercial chickens and households for indigenous chickens, as indicated by permANOVA testing of Bray-Curtis distances after ordination with non-metric multidimensional scaling (NMDS) (Fig. 2A). Bacterial communities in general and HR-ARGs were not significantly different between breeds (Pbacteria=0.103, PHR-ARGs = 0.070). At production sites, pathogenic Listeria spp., Campylobacter spp, Salmonella spp, Klebsiella spp, Yersinia spp, Pseudomonas spp, Vibrio spp, and Leptospira spp. were less abundant among indigenous than commercial chickens after adjusting for false discovery rate (Padj<0.05, Fig. 2B). Pathogenic Escherichia  spp. was the only genus more abundant among indigenous than commercial chickens at production sites. Among 129 unique ARGs detected in commercial and indigenous chicken fecal samples at the site of production, 51 (40%) were detected in both breeds, 60 (46%) only in commercial chickens, and 18 (14%) only in indigenous chickens. The most abundant HR-ARGs among both breeds were tetQ, tetW, ant6-Ia, ermF, and mefA. Multiple high-risk tetracycline resistance genes, including tet40, tetQ, tetW, and tetX were significantly more abundant in commercial chicken feces than indigenous chicken feces (Fig. 2C-D).

### Commercial and indigenous chicken fecal microbiomes and resistomes are compositionally distinct at market sites.
Commercial and indigenous chickens are sold at the same markets in Maputo; fecal samples were collected from shared cages after arriving at markets. Despite sharing the same immediate environment, we observed that commercial and indigenous chickens harbored distinct bacterial communities and ARGs at market (Pbacteria= 0.0001, PARGs=0.0001) as indicated by permANOVA testing of scaled Bray-Curtis distances (Fig. 3A). Both breeds harbored distinct communities of human pathogens and HR-ARGs, as well (Ppathogens=0.003, PHR-ARGs=0.001). Pathogenic species that were differentially abundant between breeds at the site of production, e.g., Listeria spp., Campylobacter spp., and Salmonella spp., were not differentially abundant at market. However, pathogenic species of the genus Enterococcus were significantly less abundant among indigenous than commercial chickens at market after adjusting for FDR (Padj < 0.05, Fig. 3B).  Of all the ARGs examined, only the erm(F) gene, which confers resistance to erythromycin antibiotics, was more abundant among commercial than indigenous chicken fecal samples (Fig. 3C-D) at market; previous differences in tetracycline resistance gene abundance that we observed between breeds at production sites were not apparent at market. Among 122 unique ARGs detected in market fecal samples, 55 (45%) were detected in both breeds at market sites, 41 (34%) only among commercial chickens and 26 (21%) only among indigenous chickens. 

Commercial chickens sampled at market harbored a greater number of bacterial species and a greater number of pathogenic species than commercial chickens sampled at the farm level (Pbacteria=0.002, Ppathogen=0.006), though we observed no differences in species richness, diversity, or taxa abundance among indigenous chicken feces sampled at households versus at market. Pathogenic Listeria spp., Salmonella spp., Klebsiella spp., Enterobacter spp., Pseudomonas spp., Vibrio spp., and Treponema spp. were relatively less abundant among commercial chickens sampled at markets versus at farms after adjusting for FDR (Padj < 0.05). Commercial chickens also harbored distinct communities of ARGs at markets versus at farms (P=0.023). Among 136 unique ARGs detected in commercial chicken fecal samples, 71 (52%) were detected among both farm and market samples, 40 (30%) among only farm samples and 25 (18%) among only market samples. Along with 5 other ARGs, HR-ARGs Aph(3’)-la, ermF, and tetX were significantly more abundant at farms than at markets. 

## Carcass Samples
Overall, we detected 22,851 bacterial species in carcass samples, of which 4,700 (21%) were uniquely identified in commercial chicken processing samples and 68 (<1%) were uniquely identified in indigenous chicken processing samples. Among bacterial species, 118 (0.5%) were identified as pathogenic bacteria, of which 13 (11%) were uniquely detected in commercial chicken carcass samples. All pathogens identified in indigenous chicken carcass samples were also observed among commercial chicken samples.  The most abundant bacterial genera across all processing samples were Aeromonas spp., Acinetobacter spp., Chlamydia spp., and Escherichia spp. Compared to chicken fecal samples. a substantially lower percentage of bacterial species detected in chicken processing samples were established human pathogens (7%).  We detected 141 unique ARGs in processing samples, of which 140 (99%) were uniquely identified in commercial chicken processing samples. Only one ARG was detected among indigenous chicken processing samples (tetE), although this ARG was also detected in commercial chicken processing samples. HR-ARGs were only detected in commercial chicken processing samples; 26 unique HR-ARGs were detected.  


### Many, but not all,  bacterial pathogens and ARGs present in chicken fecal samples are also present in carcass samples sold to consumers.
Among both commercial and indigenous chickens, all bacterial pathogens detected in fecal samples from production and market sites were also detected in carcass samples. The most abundant pathogens on chicken carcasses included Aeromonas spp. (56% of pathogen reads), Acinetobacter spp. (13%), Chlamydia spp. (6%), and Escherichia spp. (3%).   Commercial and indigenous chicken carcasses harbored significantly different communities of human pathogens (P=0.04), mirroring patterns observed in chicken feces. Similarly, HR-ARGs detected in commercial chicken fecal samples were also detected on commercial chicken carcasses, with Tet39 (28% of reads), srmB (19%), and sul2 (18%) being the most abundant HR-ARGs on commercial chicken carcasses that likely originated from chicken feces. Unusually, while HR-ARGs were detected in indigenous chicken feces, we did not detect any HR-ARGs among indigenous chicken carcasses (Fig. 4B). 

### Consumers are exposed to additional high-risk ARGs via commercial chicken carcasses that are not necessarily introduced from chicken feces. 
Among 166 unique ARGs detected among commercial chicken fecal and carcass samples at market sites, 70 (42%) were detected among carcass samples only.  Among the 70 ARGs that were uniquely detected in commercial chicken carcass samples that were not detected in the feces of commercial chickens at market, the most abundant were qnrS2 (7.04 log10 FPGE, detected in 21 of 42 samples ), which confers resistance to quinolone antibiotics, ampS (6.75 log10 FPGE, in 13 samples), which confers resistance to ampicillin, crpP (6.69 log10 FPGE in 1 sample) which can confer resistance against ciprofloxacin47,  tetE (6.68 log10 FPGE in 26 samples), and tetS (6.13 log10 FPGE in 16 samples) which both confer resistance against tetracycline antibiotics. 45 (64%) of the 70 ARGs were detected in rinse water and carcass samples, but not fecal samples, suggesting rinse water could be a potential source of these ARGs to chicken carcasses  . Among 30 HR-ARGs detected among commercial chicken fecal and carcass samples at market sites, 21 (70%) were detected among both fecal and carcass samples, 6 (20%) among fecal samples only, and 3 (10%) among carcass samples only. Three (10%) HR-ARGs that were uniquely detected in carcass but not fecal samples included ant(2)-Ia   aph(3)-IIIa, and mphE.   Of these, only aph(3)-IIIa was uniquely detected in carcass but not rinse water samples. HR-ARGs aadA5 and ermC were detected exclusively in rinse water and not in carcass samples and 23 other HR-ARGs were detected in both carcass and rinse water samples. There was no significant difference in overall composition of ARGs between rinse water and carcass samples (P=0.63).  
