# Processing

## Carcass Rinse Samples

```{r car-setup, include=FALSE} 
today <- Sys.Date()
pacman::p_load(phyloseq, vegan, ggplot2, ggpubr, microViz, corncob, ggraph, DT, readr, dplyr, tidyverse, gridExtra, microbiome, metagMisc, scales, GUniFrac, kableExtra, optimx, edgeR, xaringan, xaringanExtra, magick, MicEco)

physeq <- readRDS("Data/phyloseq_obj_2024-04-07.rds")
pathseq <- readRDS("Data/pathseq_obj_2024-02-27.rds")
ARGseq <- readRDS("Data/ARGseq_obj_2024-04-22.rds")
clinseq <- readRDS("Data/clinseq_obj_2024-04-18.rds")
phy_meta <- read.csv("Data/phy_meta_2024-01-30.csv")
pathogens <- read.csv("Data/pathogens_2024-01-30.csv")
ARG <- read.csv("Data/ARG_2024-01-30.csv")

## Pathogens 
phycar <- subset_samples(physeq, Carcass==1)
pathcar <- subset_samples(pathseq, Carcass==1)
argcar <- subset_samples(ARGseq, Carcass==1)
clincar <- subset_samples(clinseq, Carcass==1)

# Custom colors for plotting
custom_colors <- c(
  "Commercial/Farm/Fecal, N=4" = "darkolivegreen1",
  "Commercial/Market/Fecal, N=8" = "darkolivegreen3",
  "Commercial/Market/Carcass, N=42" = "darkolivegreen4",
  "Indigenous/Household/Fecal, N=7" = "lightblue1",
  "Indigenous/Market/Fecal, N=7" = "lightblue3",
  "Indigenous/Market/Carcass, N=7" = "lightblue4",
  "Market Rinse Water, N=26" = "goldenrod"
)



```


```{r venn-car, include=FALSE}
### Venn Diagrams
### Bacteria 
baccar <- subset_samples(physeq, Carcass==1)

### Venn Diagram
bacvenn <- ps_venn(
  baccar,
  group = "breed",
  fraction = 0,
  weight = FALSE,
  relative = TRUE,
  plot = TRUE, 
  labels=list(cex=1),
  main = "Bacteria",
  
  quantities = list(cex=1.5, type = c('counts',"percent")),
  
  fill=c("Commercial" = "darkolivegreen3", 
         "Indigenous" = "lightblue3")
  
)

## Pathogen venn diagram 
pathcar <- subset_samples(pathseq, Carcass==1)
### Venn Diagram
pathvenn <- ps_venn(
  pathseq,
  group = "Group",
  fraction = 0,
  weight = FALSE,
  relative = TRUE,
  plot = TRUE, 
  labels=list(cex=1),
  main = "Pathogens",
  
  quantities = list(cex=1.5, type = c('counts',"percent")),
  
  fill=c("Commercial" = "darkolivegreen3", 
         "Indigenous" = "lightblue3")
  
)

###ARGs 
argvenn <- ps_venn(
  argcar,
  group = "breed",
  fraction = 0,
  weight = FALSE,
  relative = TRUE,
  plot = TRUE, 
  labels=list(cex=1),
  main = "Carcass ARGs",
  
  quantities = list(cex=1.5, type = c('counts',"percent")),
  
  fill=c("Commercial" = "darkolivegreen3", 
         "Indigenous" = "lightblue3")
  
)

```
```{r venn-car-viz, echo=FALSE, warning=FALSE}
ggarrange( bacvenn, pathvenn, argvenn, ncol=2, nrow=2,  labels = c("Bacteria", "Pathogens", "ARGs", "High-Risk ARGs"), 
                    font.label = list(size = 20)) 

```



```{r stack-car, include=FALSE}
### Stacked Bars 
### Bacteria
phy_df <- phyloseq_to_df(phycar, addtax=T)

df_long <- phy_df%>% 
  gather(key="ID", value="count", -c("OTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"))
# Genus & species name
df_long$g.species <- paste0(substr(df_long$Genus, 1, 1), ".", " ", df_long$Species)

df_stack <- merge(df_long, phy_meta, by="ID")
phyla = aggregate(df_stack$count,
                  by = list(df_stack$Phylum),
                  FUN = sum)
phyla$num <- phyla$x
phyla$Phylum <- phyla$Group.1
phyla <- phyla[with(phyla,order(-num)),]

phyla <-  na.omit(phyla[-7, ][1:5, ])

phylist <- (phyla$Phylum)

df_stack$phystack <- NA

phydat1 <- df_stack[df_stack$Phylum %in% phylist,]
phydat1$phystack <- phydat1$Phylum

phydat2 <- df_stack[!df_stack$Phylum %in% phylist,]
phydat2$phystack <- "Other"

phydat <- rbind(phydat1, phydat2)
# Reorder the 'Category' variable based on the 'Value' variable
phydat$phystack <- factor(phydat$phystack, levels=c( 'Other', "Proteobacteria", "Firmicutes"    , "Chlamydiae"  ,   "Bacteroidetes" , "Actinobacteria"  ))

# Order the levels consistently across all data frames
#phydat$Group <- factor(phydat$Group, levels = desired_order)
# Define the desired order of x-axis labels
unique_categories <- unique(phy_df$loc.type.n)

#stacked bar chart
bac_stack <- phydat %>% 
  ggplot() + 
  geom_bar(aes(x=labels, y=count, fill=phystack, color=phystack), stat="identity", position="fill") + 
  #ggtitle("Proportional Abundance of Bacterial Phyla") + 
  ylab("Proportional Abundance") + theme_classic() +  theme(#text = element_text(size = 20),
    legend.title=element_blank(), text=element_text(size=16)) + 
  xlab("") + scale_y_continuous(labels = scales::percent_format(scale = 100),  # Format y-axis as percentages
                                limits = c(0, 1)) 

## Path Stack 
phy_df <- phyloseq_to_df(pathcar, addtax=T)

df_long <- phy_df%>% 
  gather(key="ID", value="count", -c("OTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"))
# Genus & species name
df_long$g.species <- paste0(substr(df_long$Genus, 1, 1), ".", " ", df_long$Species)

df_stack <- merge(df_long, phy_meta, by="ID")
phyla = aggregate(df_stack$count,
                  by = list(df_stack$g.species),
                  FUN = sum)
phyla$num <- phyla$x
phyla$g.species <- phyla$Group.1
phyla <- phyla[with(phyla,order(-num)),]

phyla <-  na.omit(phyla[1:5, ])

phylist <- (phyla$g.species)

df_stack$phystack <- NA

phydat1 <- df_stack[df_stack$g.species %in% phylist,]
phydat1$phystack <- phydat1$g.species

phydat2 <- df_stack[!df_stack$g.species %in% phylist,]
phydat2$phystack <- "Other"

phydat <- rbind(phydat1, phydat2)
# Reorder the 'Category' variable based on the 'Value' variable
phydat$phystack <- factor(phydat$phystack, levels=c( "Other", "E. coli"  ,     "K. pneumoniae" ,"E. hormaechei", "S. enterica" ,  "S. flexneri"   ))

# Define the desired order of x-axis labels
unique_categories <- unique(phy_df$loc.type.n)

#stacked bar chart
path_stack <- phydat %>% 
  ggplot() + 
  geom_bar(aes(x=labels, y=count, fill=phystack, color=phystack), stat="identity", position="fill") + 
  #ggtitle("Proportional Abundance of Pathogens") + 
  ylab("Proportional Abundance") + theme_classic() +  theme(#text = element_text(size = 20),
    legend.title=element_blank(), text=element_text(size=16)) + 
  xlab("") + scale_y_continuous(labels = scales::percent_format(scale = 100)) 

### ARGs
## Most abundant ARGs
car_args <- subset(ARG, ARG$Carcass==1)
top.args = aggregate(car_args$TotalIDs,
                     by = list(car_args$name2),
                     FUN = sum)
top.args$num <- top.args$x
top.args$name2 <- top.args$Group.1
top.args <- top.args[with(top.args,order(-num)),]
top.args <-  na.omit(top.args[1:5, ])

arglist <- (top.args$name2)

car_args$argstack <- NA 
argdat1 <- car_args[car_args$name2 %in% arglist,]

argdat1 <- car_args[car_args$name2 %in% arglist,]
argdat1$argstack <- argdat1$name2

argdat2 <- car_args[!car_args$name2 %in% arglist,]
argdat2$argstack <- "Other"

argdat <- rbind(argdat1, argdat2)

# Reorder the 'Category' variable based on the 'Value' variable

argdat$argstack <- factor(argdat$argstack, levels=c( "Other","tet(39)"     , "erm(B)"  ,    "qnrS2"  ,  "sul2" , "aph(3'')-Ib" ))

# Order the levels consistently across all data frames

arg_stack <-  argdat %>% ggplot(aes(x=labels,y=TotalIDs)) + 
  geom_bar(aes(fill=argstack, color=argstack), stat="identity", position="fill") + 
 # ggtitle("Proportional Abundance of AMR Genes") + 
  ylab("Proportional Abundance") +xlab("")+ theme_classic() +  theme( legend.title=element_blank(), text=element_text(size=16))

### hr-ARGs

## Most abundant ARGs
HR_ARG <- subset(car_args, car_args$clinical==1)
top.args = aggregate(HR_ARG$TotalIDs,
                     by = list(HR_ARG$name2),
                     FUN = sum)
top.args$num <- top.args$x
top.args$name2 <- top.args$Group.1
top.args <- top.args[with(top.args,order(-num)),]
top.args <-  na.omit(top.args[1:5, ])

arglist <- (top.args$name2)

HR_ARG$argstack <- NA 
argdat1 <- HR_ARG[HR_ARG$name2 %in% arglist,]

argdat1 <- HR_ARG[HR_ARG$name2 %in% arglist,]
argdat1$argstack <- argdat1$name2

argdat2 <- HR_ARG[!HR_ARG$name2 %in% arglist,]
argdat2$argstack <- "Other"

argdat <- rbind(argdat1, argdat2)

# Reorder the 'Category' variable based on the 'Value' variable

argdat$argstack <- factor(argdat$argstack, levels=c( "Other", "erm(B)"  ,  "sul2" ,  "aph(3'')-Ib", "aph(6)-Id"  , "tet(L)"    ))

# Order the levels consistently across all data frames

hr_arg_stack <-  argdat %>% ggplot(aes(x=labels,y=TotalIDs)) + 
  geom_bar(aes(fill=argstack, color=argstack), stat="identity", position="fill") + 
 # ggtitle("Proportional Abundance of AMR Genes") + 
  ylab("Proportional Abundance") +xlab("")+ theme_classic() +  theme( legend.title=element_blank(), text=element_text(size=16))


```



```{r stack-car-viz, echo=FALSE, warning=FALSE}
ggarrange( bac_stack, path_stack, arg_stack, hr_arg_stack, ncol=2, nrow=2,  labels = c("Bacteria", "Pathogens", "ARGs", "High-Risk ARGs"), 
                    font.label = list(size = 16)) 

```



```{r nmds-car, include=FALSE}
## Bacteria NMDS
physeq_fixed <- physeq %>%
  tax_fix(
    min_length = 2,
    unknowns = c("sp. ANNP30", "Ponticoccus"),
    sep = " ", anon_unique = TRUE,
    suffix_rank = "classified"
  )

bac_car <- subset_samples(physeq_fixed, Carcass == 1)

# Transform phyloseq object
physeq.rel <- microbiome::transform(bac_car, "compositional")
otu <- abundances(physeq.rel)
meta <- meta(physeq.rel)
# Significance Test (PERMANOVA)
formula_str <- paste("t(otu) ~", "breed")  # Create the formula string
permanova <- adonis2(as.formula(formula_str), data = meta, permutations = 999999, method = "bray")
p_value <- sprintf("%.4f", permanova$`Pr(>F)`[1])  # Format p-value to four decimal places

### Side Density Plot 
bac_nmds <- bac_car %>%
  tax_transform("identity", rank = "Phylum") %>%
  dist_calc(dist = "bray") %>%
  ord_calc("NMDS") %>%
  ord_plot(color = "loc.type.n", shape = "breed", size = 3) +
  stat_ellipse(aes(group = loc.type.n)) + ## add ellipses
  scale_color_manual(values=custom_colors)+
  theme_bw() + ggtitle(paste0("Bacteria Composition \n P-Value=", p_value)) + 
  ggside::geom_xsidedensity(aes(fill = loc.type.n), alpha = 0.5, show.legend = FALSE) +
  ggside::geom_ysidedensity(aes(fill = loc.type.n), alpha = 0.5, show.legend = FALSE) +
  ggside::theme_ggside_void() + scale_fill_manual(values=custom_colors) +  theme(
      text = element_text(size = 12),           # General text size
      legend.title = element_blank(),           # No legend title
      plot.title = element_text(size = 12),     # Plot title size
      axis.title = element_text(size = 12),     # Axis titles size
      axis.text = element_text(size = 12),      # Axis text size
      legend.text = element_text(size = 12)     # Legend text size
    )

## Pathogen NMDS 
# Transform phyloseq object
physeq.rel <- microbiome::transform(pathcar, "compositional")
otu <- abundances(physeq.rel)
meta <- meta(physeq.rel)
# Significance Test (PERMANOVA)
formula_str <- paste("t(otu) ~", "breed")  # Create the formula string
permanova <- adonis2(as.formula(formula_str), data = meta, permutations = 999999, method = "bray")
p_value <- sprintf("%.3f", permanova$`Pr(>F)`[1])  # Format p-value to four decimal places

### Side Density Plot 
path_nmds <- pathcar %>%
  tax_transform("identity", rank = "Genus") %>%
  dist_calc(dist = "bray") %>%
  ord_calc("NMDS") %>%
  ord_plot(color = "loc.type.n", shape = "breed", size = 3) +
  stat_ellipse(aes(group = loc.type.n)) + ## add ellipses
  scale_color_manual(values=custom_colors)+
  theme_bw() + ggtitle(paste0("Pathogen Composition \n P-Value=", p_value)) + 
  ggside::geom_xsidedensity(aes(fill = loc.type.n), alpha = 0.5, show.legend = FALSE) +
  ggside::geom_ysidedensity(aes(fill = loc.type.n), alpha = 0.5, show.legend = FALSE) +
  ggside::theme_ggside_void() + scale_fill_manual(values=custom_colors) + theme(
      text = element_text(size = 12),           # General text size
      legend.title = element_blank(),           # No legend title
      plot.title = element_text(size = 12),     # Plot title size
      axis.title = element_text(size = 12),     # Axis titles size
      axis.text = element_text(size = 12),      # Axis text size
      legend.text = element_text(size = 12)     # Legend text size
    )

```
```{r nmds-proc-viz, echo=FALSE, warning=FALSE}
ggarrange( bac_nmds, path_nmds,  ncol=2,  labels = c("Bacteria", "Pathogens"), 
                    font.label = list(size = 10)) 

```


```{r daa-car, include=FALSE}
source("Data/daa_function.R")

### DAA BACTERIA 
baccar<- phycar %>%  tax_glom("Phylum")

#DIFFERENTIAL ABUNDANCE BETWEEN BREEDS (AMONG PRODUCTION SITE)
daa_car <- differentialTest(formula = ~ Indigenous,
                            phi.formula = ~ Indigenous,
                            formula_null = ~ 1,
                            phi.formula_null = ~ Indigenous,
                            test = "Wald", boot = FALSE,
                            full_output=FALSE,
                            data = baccar,
                            fdr_cutoff = 0.05)

bac_daa <- plot.differentialTest(daa_car, level= "Phylum")

### DAA PATH

pathcar <- pathcar %>% tax_glom("Genus")

#DAA ARGS
daa_path <- differentialTest(formula = ~ Indigenous,
                             phi.formula = ~ Indigenous,
                             formula_null = ~ 1,
                             phi.formula_null = ~ Indigenous,
                             test = "Wald", boot = FALSE,
                             full_output=FALSE,
                             data = pathcar,
                             fdr_cutoff = 0.05)

path_daa <- plot.differentialTest(daa_path, level= "Genus")

```



```{r daa-prod-viz, echo=FALSE, warning=FALSE}
ggarrange( bac_daa, path_daa, ncol=2,   labels = c("Bacteria", "Pathogens"), 
                    font.label = list(size = 10)) 

```



```{r heat-car, include=FALSE}

### Pathogen HEatmaps
pathseq_g <- tax_glom(pathseq, "Genus")

taxaorder <- unique(taxa_names(pathseq_g))

pathseq_car <- subset_samples(pathseq_g, Carcass==1)
pathseq_car_com <- subset_samples(pathseq_car, breed=="Commercial")
pathseq_car_ind <- subset_samples(pathseq_car, breed=="Indigenous")

hm_path_car_com <-plot_heatmap(pathseq_car_com, taxa.label= "Genus", taxa.order=taxaorder, title = "Commercial", trans = log_trans(10), low="#e3fa9e", high="#59730d", na.value="white")  + theme_classic() + theme(text=element_text(size=12))

hm_path_car_ind <-plot_heatmap(pathseq_car_ind, taxa.label= "Genus", taxa.order=taxaorder,  title = "Indigenous",   trans = log_trans(10), low="#d6f5f4", high="#074e54", na.value="white") + theme_classic() + theme(text=element_text(size=12))

### HR-ARG heatmap 

clinseq_g <- tax_glom(clincar, "Genus")

taxaorder <- unique(taxa_names(clinseq_g))

clinseq_com <- subset_samples(clinseq_g, breed=="Commercial")

hm_clin_car_com <-plot_heatmap(clinseq_com, taxa.label= "Genus", taxa.order=taxaorder, title = "Commercial Carcass Samples", trans = log_trans(10), low="#e3fa9e", high="#59730d", na.value="white")  + theme_classic() + theme(text=element_text(size=12)) 

clinseq_g <- tax_glom(clincar, "Genus")

taxaorder <- unique(taxa_names(clinseq_g))

clinseq_car <- subset_samples(clinseq_g, Group=="Processing")
clinseq_car_com <- subset_samples(clinseq_car, breed=="Commercial")

clinseq_com <- subset_samples(clinseq_g, breed=="Commercial")

hm_clin_car_com <-plot_heatmap(clinseq_car_com, taxa.label= "Genus", taxa.order=taxaorder, title = "Commercial Carcass Samples", trans = log_trans(10), low="#e3fa9e", high="#59730d", na.value="white")  + theme_classic() + theme(text=element_text(size=12)) 


```

```{r heat-mkt-viz, echo=FALSE, warning=FALSE}
ggarrange( hm_path_car_com , hm_path_car_ind ,  hm_clin_car_com, hm_clin_car_ind, ncol=2, nrow=2,  labels = c("Bacteria", "Pathogens", "ARGs", "High-Risk ARGs"), 
                    font.label = list(size = 10)) 

```
