# Discussion & Conclusion {-}

In this study, we employed metagenomic shotgun sequencing to describe poultry microbiomes and resistomes across the supply chain in Maputo, Mozambique. We took this approach to broadly characterize pathogen and ARG exposures at each point in the supply chain to better understand potential risks to human health. While targeted amplification of enteropathogenic Campylobacter spp. and Salmonella spp. revealed increasing contamination of chicken fecal and carcass samples along the value chain in the Cheep Cheep study22, this follow-up analysis reveals a wider array of pathogens and ARGs in a subset of the same fecal and carcass samples. Human pathogens and HR-ARGs persisted along the poultry value chain and contaminated slaughtered chicken carcasses purchased by consumers. While most ARGs appeared to originate in chicken feces, many did not, suggesting alternate sources of contamination in the wet market setting. Rinse water is a likely source of additional contamination, but other environmental sources such as vendors, surfaces, and pests, likely explain the greater diversity of pathogens and ARGs observed on carcasses.  Finally, we find that commercial and indigenous chickens pose distinct hazards to consumers despite being housed together at market  prior to sale. Overall, our findings suggest markets as a potential site of exposure to pathogens and ARGs from poultry and poultry products. 
We observed differences in pathogen and ARG abundances between commercial and indigenous chickens that persisted along the value chain. At production sites, indigenous chicken fecal samples carried significantly lower relative abundance of pathogens including Listeria, Campylobacter, Escherichia, Salmonella, Klebsiella, Yersinia, Pseudomonas, Vibrio, and Leptospira than commercial chickens.  Greater pathogen burden among commercial chickens at production sites may result from age differences between groups, with commercial chickens sampled at farms likely younger than indigenous chickens sampled at households. Chicken microbiome abundance and diversity reach a plateau at 7 days, but compositional changes continue to occur throughout their development48. Further research is needed to parse whether the differences we observed in pathogen load at the site of production were due to differences in chicken age or truly due to breed. We also observed that commercial chicken fecal microbiomes and resistomes, but not those of indigenous chickens, differed upon arrival at market. This difference could be a result of age; although commercial and indigenous chickens brought to market have reached maturity, commercial chickens are sold at markets at an average age of 60 days old49 compared with indigenous household chickens at an average age of 24 weeks50 according to studies in eastern and southern Africa. Alternatively, it is also possible that stress induced by commercial transportation factors51 including heat52 and crowding53 resulted in different microbiome profiles between farm and market commercial chicken fecal samples. Importantly, while commercial chicken fecal microbiomes and resistomes differed upon arrival at market, they continued to remain distinct from indigenous chickens. We hypothesized that market holding pens would provide opportunities for pathogen and AMR bacterial transmission among poultry of distinct breeds and origins. However, while commercial and indigenous chickens were housed together upon arrival at market sites, we found no evidence that that their microbiomes or resistomes were more similar at market than production sites.  

We also observed that bacteria and ARGs harbored by chickens at farms and markets may persist through processing and pose a threat to the health of consumers.  The most abundant pathogenic species detected in carcass samples included enteropathogens E. coli, K. pneumonia, S. enterica, and S. flexneri, as well as the opportunistic pathogen E. hormaechei, which is often seen in healthcare-associated infections54. Detection of these pathogens is notable because consumption of contaminated poultry and egg products are linked with over 70% of human salmonellosis (S. enterica) cases in the United States55. Meanwhile, while K. pneumoniae is less commonly considered a foodborne pathogen56, K. pneumonia is known to develop and carry ESBL (extended-spectrum beta-lactamase) antimicrobial resistance genes and is therefore considered a significant threat to public health57–59.  Tet39, which confers resistance against tetracycline60, was the most abundant HR-ARG among commercial chicken carcass samples (none were detected in indigenous chicken carcass samples); tetracycline resistance was reported in 62% of 120 S. aureus isolates tested in a similar “farm-to-fork” study of poultry and poultry products performed in South Africa61 and in 100% of 24 Campylobacter spp. isolates from broiler chicken carcasses sampled at markets and slaughterhouses in Maputo, Mozambique62.  
Several HR-ARGs including ant(2)-Ia,  aph(3)-IIIa, and mphE were detected  only in processed carcass samples and not at previous sites along the value chain. The ARGs ant(2)-Ia63 and aph(3)-IIIa64confer resistance against aminoglycosides (including gentamicin, amikacin, tobramycin, neomycin, and streptomycin) while mphE60 confers resistance against macrolides (including erythromycin, roxithromycin, azithromycin and clarithromycin). The unique detection of these genes on commercial chicken carcass samples, but not fecal samples, could indicate contamination from human, rinse water, or other environmental sources during chicken processing activities65,66. Commercial carcass and rinse water microbiomes and resistomes were not compositionally different from each other, indicating that rinse water is likely a meaningful representation of pathogen and ARG exposures to consumers. Genes conferring resistance against aminoglycoside, folate pathway antagonist, macrolide, lincosamide, streptogramin B, quinolone, and tetracycline clinical antibiotic classes were detected among carcass and rinse water samples. The presence of these ARGs in consumer poultry products may increase their risk of being mobilized by human microbes during food handling, preparation, or consumption. 
 Overall, as poultry production increases in LMICs, foodborne exposures to pathogens and HR-ARGs are likely to grow. Live and wet markets are an affordable and socially/culturally important source of food and income for many communities, but conditions in many markets are conducive to the spread of infectious disease and antimicrobial resistant pathogens3. It is imperative to maintain cultural sensitivity while advocating for resources to prevent the spread of infectious diseases in these settings. Resources for vendors to prevent cross-contamination of their products may mitigate disease transmission risk while facilitating sustainable food systems.  
 
This study had several strengths. The use of metagenomic sequencing to characterize samples across the poultry value chain contributes novel insights and supports the use of an emerging "farm-to-fork approach” in foodborne disease research61,67,68.  Our study, nested within a larger study that mapped the poultry value chain prior to selecting sites for sampling and modelled transmission risk at various sites, helps to provide a comprehensive understanding of pathogen and ARG exposures within this system. This study also provides metagenomic characterization of poultry in Maputo, Mozambique, a setting with poorly described poultry pathogen and ARG prevalence. Finally, distinguishing between indigenous and commercial chickens contributes to understanding of microbiome and resistome differences between breeds. This study reflects the characteristically exploratory nature of “omics” approaches and provides foundational evidence for further investigation69. 

 There were also some limitations to this study. First, relatively few samples were available from farms and markets and no samples were available from other key points along the poultry value chain, including depots (where commercial chicks are purchased) and neighborhood food stalls, which limited the scope of our analysis. Samples were collected during winter months of June and July in the southern hemisphere22; we therefore cannot address seasonal trends in ARG detection reported in other southern African poultry studies70.  Samples across sites were not paired, so we are unable to conclude temporal shifts among individual chickens from farm to market and processing.  Additionally, while untargeted sequencing offers the advantage of detecting a wide variety of strains and ARGs, metagenomic sequencing data may not accurately represent true exposure of consumers to pathogenic or antibiotic-resistant bacteria due to the detection of non-infectious DNA fragments and low pathogen concentrations. As such, our findings represent hazards rather than risks of foodborne illness2. Concentrations of genetic material in fecal and water samples are known to be highly variable, with much higher concentrations in fecal samples than water samples71. This is consistent with our samples, in which sequencing depth was much greater among fecal samples than rinse water or carcass samples. Differences between carcass, rinse water, and fecal samples are therefore likely to be attributable at least in part to differences in sample type rather than differences in actual contamination. 
 
 
## Conclusion {-}
Metagenomic analysis of chicken fecal and processing samples reveals distinct patterns of pathogen and ARG contamination along the poultry value chain in Maputo, Mozambique. Bacterial pathogens and ARGs present in fecal samples are also present in carcass samples sold to consumers with distinct hazards potentially posed by indigenous versus commercial chicken carcasses. Chicken carcasses are also contaminated with additional high-risk AMR bacteria that are not necessarily introduced from chicken feces. Overall, these results indicate the potential for informal markets as a critical juncture in the spread of pathogenic and antimicrobial resistant bacteria in a community.  


